/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    {
      type: "doc",
      label: "Introduction",
      id: "intro",
    },
    {
      type: "category",
      label: "Extension and In-app browser",
      collapsed: false,
      items: [
        "integrating/detecting-the-provider",
        "integrating/establishing-a-connection",
        "integrating/account-data",
        "integrating/signing-a-message",
        "integrating/sending-a-transaction",
        "integrating/errors",
      ],
    },
    {
      type: "doc",
      label: "Privacy policy",
      id: "privacy-policy",
    },
  ],
};

module.exports = sidebars;
